name: Build and publish a Docker image to ghcr.io
on:
  release:
    types: [ published ]
  push:
    branches:
      - master
jobs:
  docker_publish:
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: false          
    - name: Set up docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: "ghcr.io/${{ github.repository }}"
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
permissions:
  contents: read
  packages: write
